apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chadbot.fullname" . }}
data:
  ADMIN_USERNAME: {{ .Values.chad.adminUser | b64enc | quote }}
  AUTH_TOKEN: {{ .Values.chad.botToken | b64enc | quote }}
  BIND_IP: {{ .Values.chad.bindIP | default "0.0.0.0" | b64enc | quote }}
  BIND_PORT: {{ "7357" | b64enc | quote }}
  CALLBACK_URL: {{ .Values.chad.callbackURL | b64enc | quote }}
  CHAT_DOMAIN: {{ .Values.chad.url | b64enc | quote }}
  EXTERNAL_MM_URL: {{ .Values.chad.externalUrl | b64enc | quote }}
  CHANNEL_PREFIX: {{ .Values.chad.channelPrefix | b64enc | quote }}
  CONFIG_CHANNEL: {{ .Values.chad.settingsChannel | b64enc | quote }}
