apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chadbot.fullname" . }}
data:
  BOT_TOKEN: {{ .Values.chad.botToken | b64enc | quote }}
  BOT_TEAM: {{ .Values.chad.team | b64enc | quote }}
  MATTERMOST_URL: {{ .Values.chad.url | b64enc | quote }}
  EXTERNAL_MM_URL: {{ .Values.chad.externalUrl | b64enc | quote }}
  MATTERMOST_PORT: {{ .Values.chad.port | b64enc | quote }}
  WEBHOOK_HOST: {{ .Values.chad.callbackUrl | b64enc | quote }}
  WEBHOOK_HOST_PORT: {{ .Values.chad.callbackPort | b64enc | quote }}
  SETTINGS_CHANNEL: {{ .Values.chad.settingsChannel | b64enc | quote }}
